name: Build Android APK with Kivy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install buildozer cython

      - name: Install Android SDK and NDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip
          yes | tools/bin/sdkmanager --licenses
          yes | tools/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.2" "ndk;23.1.7779620"
                
      - name: Run Buildozer
        run: |
          cd lab7
          echo y | buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: apk-file
          path: bin/*.apk
